version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads:/app/uploads
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=document_ai
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=document_ai
      - SECRET_KEY=tu_clave_secreta_aqui
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - db
      - mongo
      - ollama

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: document_ai
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  mysql_data:
  mongo_data:
  ollama_data:
  uploads:
