version: '3.8'

services:
  app:
    build: .
    environment:
      - ENVIRONMENT=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  mysql_data:
  mongo_data:
  ollama_data: