version: '3.8'

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    extends:
      file: docker-compose.yml
      service: db
    deploy:
      resources:
        limits:
          memory: 1G

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    image: redis:7.0
    deploy:
      resources:
        limits:
          memory: 512M

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro